### ISSUE TITLE
卡券、红包接口

### ISSUE THREAD

**Issue by 651778286** [sword-org/wechat4j#27]
卡券、红包接口现在很火，很多人需要，想跟各位讨论讨论将这两个接口打通

**Comment by chengn** [comment]
这个建议很好，此项目中当初建好了接口的包，鉴于时间所限和开发人员的资源欠缺，这块功能没有进展，抱歉。
另外，非常欢迎你能贡献这部分代码

**Comment by 651778286** [comment]
非常感谢，我也正有此意向，也希望能够加入到这个开源项目中
不过最近手头项目工作很紧，稍晚些时候我会安排时间来做这件事，谢谢您的回复
