### ISSUE TITLE
引用sword-lang时的JAXB操作XML的字符集问题

### ISSUE THREAD

**Issue by uncoseason** [sword-org/wechat4j#28]
sword中JAXB调用默认本地编码，能不能照顾下广大的windows开发环境的同胞啊，本地默认都是GBK哦，如果用file.encoding环境变量的方式弊端太大，能不能给予可选编码的配置方式啊？3Q。

**Comment by chengn** [comment]
系统默认的编码是jvm的编码，跟本地是什么默认编码没有太大关系，可以考虑配置这个编码，但是你可以再启动服务器的时候，加上jvm的编码参数，这样就可以改动默认的jvm编码。
监狱utf-8的万能编码，我建议系统都是utf-8.你的建议我会考虑的。
谢谢

**Comment by uncoseason** [comment]
感谢
