### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by yangqinglei26** [sword-org/wechat4j#37]
获取的用户信息是乱码，请问如何设置编码

**Comment by neilrencn** [comment]
lang包中修改HttpUtils文件
return entity != null ? EntityUtils.toString(entity) : null;
在EntityUtils.toString(entity) 上增加了Consts.UTF_8编码，我用的linux操作系统，如果没有编码我返回时都是乱码～

**Comment by chengn** [comment]
关于乱码问题，原文是不想设置编码的，希望大家默认使用万能吗utf-8.由于系统和字符编码的原因，有些人可能会出现乱码，解决如下：
1、web容器的默认编码设置为utf-8，也就是把jvm的编码进行一下设置，例如如果是用的web容器是tomcat，则设置catalina.bat中启动参数，具体设置方法可以参考搜索引擎。这样你的默认编码就是utf-8
2、http get的参数乱码，如果url中有汉字出现乱码，则使用server.xml配置编码（tomcat为例）。
3、http post乱码，需要自己编写一个filter进行转码，如果使用spring的话，spring就有，可以直接配置在web.xml中。

最后，最希望的还是大家直接配置jvm为utf-8
