### ISSUE TITLE
1.1.0发版说明中出现了错别字，顺便问个问题

### ISSUE THREAD

**Issue by okuc** [sword-org/wechat4j#9]
1.1.0发版说明中出现了错别字，建议改一下。错误如下：
> 1 删除**就得**依赖包，下载最新的wechat4j依赖包全集wechat4j开发jar下载

别外，想问下，如果在sae上用1.1.0，是不是说把httpclientjar包换成4.1版本的就可以了，还是说，必须得调用sae的提供的httpclient API？

**Comment by chengn** [comment]
好的，谢谢，错别字我会修改一下。
在sae上使用1.1.0的话必须自己下载源码，修改之后重新打包一下。将httpclient换成4.1，然后修改一下相关代码，具体的修改地方我随后写一篇说明。
同时我给sae提了工单，看能不能升级一下这个jar包，bae是没有问题的。号召大家都去提吧，看提的人多了会不会给升级

**Comment by okuc** [comment]
等sae官方更新，不知道猴年马月呢，还是自已搞吧

**Comment by chengn** [comment]
新发的1.1.1稳定版支持sae。详细方法的链接地址：
https://github.com/sword-org/wechat4j/releases/tag/1.1.1
